work-css-first-section
lizaklimova/project-devs-3 pull request #6
Opened 2023-07-08 13:19 UTC by k0robova

Додала стилі та адаптив для першої секції, секції WORK.

При обмеженнях як на макеті. не завжди текст переноситься так, як треба

2023-07-08 14:55 UTC, lizaklimova commented on src/css/work.css
> +  margin-top: 120px;
заміни на маргін-ботом 40

2023-07-08 14:56 UTC, lizaklimova commented on src/css/work.css
> +  .container {
контейнери я вже додала в головному файлі стилів для медіа, повидаляй

2023-07-08 15:03 UTC, k0robova commented on src/css/work.css
> +  margin-top: 120px;
зробила)

2023-07-08 15:03 UTC, k0robova commented on src/css/work.css
> +  .container {
контейнери закоментувала - потім видалю. хай поки будуть для мене

2023-07-08 15:03 UTC, lizaklimova requested changes
контаенери кругом прибрати

2023-07-08 15:35 UTC, lizaklimova commented on src/css/work.css
> +  padding-top: 100px;
там до речі паддінг 80

2023-07-08 15:36 UTC, lizaklimova commented on src/css/work.css
> +  padding-top: 100px;
і паддінг ботом ще

2023-07-08 15:40 UTC, lizaklimova commented on src/css/work.css
> +/* .work-steps-wrap {
padding-top: 40px;
  padding-left: 20px;

2023-07-08 15:48 UTC, k0robova commented on src/css/work.css
> +  padding-top: 100px;
є + додала в адаптивах

2023-07-09 19:05 UTC, lizaklimova approved these changes

2023-07-09 19:05 UTC, merged